[package]
name = "sidrs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
name = "sidrs"

[dependencies]
extendr-api = "0.6"
indexmap = "2.2.6"
ndarray = "0.15.6"
rayon = "1.10.0"
rustc-hash = "1.1.0"
