# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_sidrs_wrappers", use_symbols = TRUE, package_name = "sidrs")

#' @docType package
#' @usage NULL
#' @useDynLib sidrs, .registration = TRUE
NULL

#' Compute the SID between two adjacency matrices.
#' @export
sid <- function(g, h) .Call(wrap__sid, g, h)

#' Compute the SID between two adjacency matrices in parallel.
#' @export
par_sid <- function(g, h) .Call(wrap__par_sid, g, h)


# nolint end
